/* DATA.JS - FULL DATABASES */
const yojijukugoList = [
  { k: "一石二鳥", m: "Killing two birds with one stone" },
  { k: "一刀両断", m: "Cutting in two with a single stroke; Taking decisive action" },
  { k: "一期一会", m: "Once-in-a-lifetime encounter; Treasure every meeting" },
  { k: "一心不乱", m: "With heart and soul; Intently and focused" },
  { k: "一念発起", m: "Being resolved to do something; Turning over a new leaf" },
  { k: "一長一短", m: "Merits and demerits; Having both strong and weak points" },
  { k: "一朝一夕", m: "In a single day; Overnight (usually 'cannot be done overnight')" },
  { k: "一喜一憂", m: "Alternating between joy and sorrow; Emotional rollercoaster" },
  { k: "一蓮托生", m: "Sharing the same fate; Being in the same boat" },
  { k: "一触即発", m: "Volatile situation; Touch-and-go" },
  { k: "一進一退", m: "One step forward, one step back; Ebbing and flowing" },
  { k: "一致団結", m: "Solidarity; Uniting as one" },
  { k: "一日千秋", m: "Waiting impatiently; One day feels like a thousand years" },
  { k: "一笑千金", m: "A smile worth a thousand pieces of gold; Captivating smile" },
  { k: "一言一句", m: "Every single word and phrase" },
  { k: "一挙両得", m: "Serving two purposes; Two birds with one stone" },
  { k: "一挙一動", m: "Every single move and action" },
  { k: "一夜漬け", m: "Cramming overnight for an exam" },
  { k: "一世一代", m: "Once in a lifetime event or performance" },
  { k: "一目瞭然", m: "Apparent at a glance; Obvious" },
  { k: "二人三脚", m: "Two people acting as one; Three-legged race" },
  { k: "二束三文", m: "Dirt cheap; A dime a dozen" },
  { k: "三位一体", m: "Trinity; Three things coming together as one" },
  { k: "三寒四温", m: "Three cold days followed by four warm days (early spring weather)" },
  { k: "三十六計", m: "Of the 36 strategies, fleeing is best (Retreat is a valid option)" },
  { k: "三日坊主", m: "One who gives up easily; A monk for three days" },
  { k: "四面楚歌", m: "Surrounded by enemies on all sides; Total isolation" },
  { k: "四苦八苦", m: "Being in dire distress; Agonizing" },
  { k: "四字熟語", m: "Four-character idiom" },
  { k: "五里霧中", m: "Lost in a fog; Totally bewildered" },
  { k: "五臓六腑", m: "The internal organs; From the bottom of one's heart" },
  { k: "七転八倒", m: "Writhing in agony; Tumbling and falling" },
  { k: "七転び八起き", m: "Fall down seven times, stand up eight; Resilience" },
  { k: "八方美人", m: "Trying to please everyone; Everybody's friend" },
  { k: "八面六臂", m: "To be highly versatile; Having eight faces and six arms" },
  { k: "十人十色", m: "Ten people, ten colors; To each their own" },
  { k: "百花繚乱", m: "A hundred flowers blooming; Gathering of beautiful/talented people" },
  { k: "百戦錬磨", m: "Veteran of a hundred battles; Highly experienced" },
  { k: "百発百中", m: "On target every time; Infallible" },
  { k: "百聞は一見", m: "Seeing is believing; A picture is worth a thousand words" },
  { k: "千変万化", m: "Innumerable changes; Kaleidoscopic" },
  { k: "千差万別", m: "An infinite variety of differences; Apples and oranges" },
  { k: "千載一遇", m: "Once in a thousand years opportunity" },
  { k: "千客万来", m: "A constant stream of customers" },
  { k: "万里の長城", m: "The Great Wall of China" },
  { k: "万事休す", m: "All is lost; There is nothing more to be done" },
  { k: "万骨枯る", m: "Thousands perish so one general can achieve fame" },
  { k: "万全の策", m: "A foolproof plan; A perfect strategy" },
  { k: "以心伝心", m: "Telepathy; Heart-to-heart communication" },
  { k: "異口同音", m: "Unanimously; Speaking with one voice" },
  { k: "異端邪説", m: "Heresy and false doctrines" },
  { k: "意気投合", m: "Hitting it off; Finding a kindred spirit" },
  { k: "意気消沈", m: "Depressed; Downhearted" },
  { k: "意気軒昂", m: "In high spirits; Triumphant" },
  { k: "意味深長", m: "Profound meaning; Full of implications" },
  { k: "因果応報", m: "Karma; What goes around comes around" },
  { k: "隠忍自重", m: "Putting up with things patiently" },
  { k: "有象無象", m: "The masses; The rabble; Mob" },
  { k: "右往左往", m: "Going back and forth in confusion; Panicking" },
  { k: "有名無実", m: "In name only; Existing only in name" },
  { k: "紆余曲折", m: "Twists and turns; Meandering" },
  { k: "海千山千", m: "A sly old dog; Someone who knows the ways of the world" },
  { k: "快刀乱麻", m: "Cutting the Gordian knot; Solving a complex problem decisively" },
  { k: "外柔内剛", m: "Gentle on the outside, tough on the inside" },
  { k: "臥薪嘗胆", m: "Enduring unspeakable hardships for the sake of vengeance or success" },
  { k: "我田引水", m: "Seeking one's own interests; Drawing water to one's own field" },
  { k: "夏炉冬扇", m: "Useless things (Summer heater, Winter fan)" },
  { k: "花鳥風月", m: "The beauties of nature; Flower, Bird, Wind, Moon" },
  { k: "花鳥諷詠", m: "Composing poetry on the beauties of nature" },
  { k: "画竜点睛", m: "Finishing touch; Putting the pupils in the painted dragon's eyes" },
  { k: "換骨奪胎", m: "Adapting an old idea/work and creating something new from it" },
  { k: "勧善懲悪", m: "Rewarding good and punishing evil" },
  { k: "感慨無量", m: "Deeply moved; Filled with deep emotion" },
  { k: "冠婚葬祭", m: "Important ceremonial occasions" },
  { k: "危機一髪", m: "Hanging by a thread; A hair's breadth from danger" },
  { k: "喜怒哀楽", m: "Human emotions; Joy, anger, sorrow, and pleasure" },
  { k: "奇想天外", m: "Fantastic; Bizarre; Completely unexpected" },
  { k: "玉石混交", m: "A mixture of wheat and chaff; Good and bad mixed together" },
  { k: "旧態依然", m: "Remaining unchanged; Stuck in the old ways" },
  { k: "九牛一毛", m: "A drop in the bucket; A single hair from nine cows" },
  { k: "共存共栄", m: "Coexistence and coprosperity" },
  { k: "虚心坦懐", m: "With an open and calm mind; Without prejudice" },
  { k: "欣喜雀躍", m: "Jumping for joy" },
  { k: "空前絶後", m: "Unprecedented and never to be repeated" },
  { k: "軽挙妄動", m: "Rash and blind action; Acting without thinking" },
  { k: "継往開来", m: "Inheriting the past and ushering in the future" },
  { k: "鶏口牛後", m: "Better to be the head of a chicken than the tail of a cow" },
  { k: "形而上学", m: "Metaphysics" },
  { k: "傾国傾城", m: "A woman of matchless beauty" },
  { k: "激励鼓舞", m: "Encouragement and inspiration" },
  { k: "堅忍不抜", m: "Indomitable perseverance; Unshakable resolve" },
  { k: "乾坤一擲", m: "Staking everything on a single throw; All or nothing" },
  { k: "言語道断", m: "Outrageous; Absurd; Unspeakable" },
  { k: "孤軍奮闘", m: "Fighting a lone battle" },
  { k: "虎視眈眈", m: "Glaring like a tiger; Watching vigilantly for an opportunity" },
  { k: "誇大妄想", m: "Megalomania; Delusions of grandeur" },
  { k: "五穀豊穣", m: "Huge harvest of grains; Bountiful harvest" },
  { k: "山紫水明", m: "Scenic beauty of mountains and rivers" },
  { k: "獅子奮迅", m: "Furious activity; Fighting like a raging lion" },
  { k: "四分五裂", m: "Torn to pieces; Completely fragmented" },
  { k: "自業自得", m: "Reaping what you sow; You asked for it" },
  { k: "自給自足", m: "Self-sufficiency" },
  { k: "自画自賛", m: "Singing one's own praises" },
  { k: "自暴自棄", m: "Desperation; Abandoning oneself to despair" },
  { k: "自由奔放", m: "Free and unrestrained; Free-spirited" },
  { k: "自縄自縛", m: "Being caught in one's own trap" },
  { k: "疾風迅雷", m: "With lightning speed; Swift and violent" },
  { k: "質実剛健", m: "Unaffected and sincere, with fortitude and vigor" },
  { k: "捲土重来", m: "Making a comeback with redoubled efforts" },
  { k: "遮二無二", m: "Recklessly; Frantically" },
  { k: "弱肉強食", m: "Survival of the fittest; Law of the jungle" },
  { k: "取捨選択", m: "Making a choice; Rejecting the bad and taking the good" },
  { k: "首尾一貫", m: "Consistency; Logical from beginning to end" },
  { k: "縦横無尽", m: "Freely; Without restriction; In all directions" },
  { k: "熟慮断行", m: "Deliberate carefully and act decisively" },
  { k: "春夏秋冬", m: "The four seasons; Spring, Summer, Autumn, Winter" },
  { k: "純情可憐", m: "Pure and innocent; Sweet and lovely" },
  { k: "諸行無常", m: "All worldly things are transitory; Impermanence" },
  { k: "初志貫徹", m: "Carrying out one's original intention to the end" },
  { k: "心機一転", m: "Changing one's attitude; Turning over a new leaf" },
  { k: "針小棒大", m: "Exaggeration; Making a mountain out of a molehill" },
  { k: "森羅万象", m: "All creation; The universe; All things in nature" },
  { k: "深謀遠慮", m: "Deep foresight and careful planning" },
  { k: "神出鬼没", m: "Elusive; Appearing and disappearing like a phantom" },
  { k: "晴耕雨読", m: "Working in the field in fair weather, reading at home in the rain" },
  { k: "生殺与奪", m: "Having the power of life and death over someone" },
  { k: "正真正銘", m: "Genuine; Authentic; True" },
  { k: "清廉潔白", m: "Pure and innocent; Upright and clean-handed" },
  { k: "絶体絶命", m: "Driven into a corner; Desperate situation" },
  { k: "前代未聞", m: "Unprecedented; Unheard-of" },
  { k: "前途洋洋", m: "Having a promising future" },
  { k: "前途多難", m: "Having many difficulties ahead" },
  { k: "創意工夫", m: "Being imaginative and creative" },
  { k: "相思相愛", m: "Mutual love" },
  { k: "大器晩成", m: "Great talents mature late; Late bloomer" },
  { k: "大言壮語", m: "Talking big; Boasting" },
  { k: "大義名分", m: "Just cause; Legitimate reason" },
  { k: "単刀直入", m: "Cutting to the chase; Getting straight to the point" },
  { k: "知行合一", m: "Action and knowledge are one" },
  { k: "中途半端", m: "Halfway; Incomplete" },
  { k: "朝令暮改", m: "Inconsistent policies" },
  { k: "直情径行", m: "Acting on impulse; Straightforward action" },
  { k: "沈思黙考", m: "Deep in thought; Musing" },
  { k: "天下泰平", m: "Peace in the world; Tranquility" },
  { k: "天真爛漫", m: "Innocent and naive; Simple and pure" },
  { k: "天変地異", m: "Natural disasters; Cataclysms" },
  { k: "天衣無縫", m: "Flawless; Perfect beauty" },
  { k: "天地無用", m: "Do not turn upside down" },
  { k: "電光石火", m: "As fast as lightning" },
  { k: "徹頭徹尾", m: "Thoroughly; Through and through" },
  { k: "転禍為福", m: "Turning misfortune into a blessing" },
  { k: "唯唯諾諾", m: "Being a yes-man; Readily agreeing to everything" },
  { k: "同床異夢", m: "Sleeping in the same bed, dreaming different dreams" },
  { k: "道聴塗説", m: "Gossip; Hearsay" },
  { k: "独立独歩", m: "Independence; Standing on one's own two feet" },
  { k: "読書三昧", m: "Being entirely engrossed in reading" },
  { k: "内憂外患", m: "Troubles at home and abroad" },
  { k: "難攻不落", m: "Impregnable; Invincible" },
  { k: "二者択一", m: "Choosing between two options" },
  { k: "日進月歩", m: "Rapid and steady progress" },
  { k: "入木三分", m: "Leaving a deep impression; Profound writing" },
  { k: "忍之一字", m: "Endurance is everything" },
  { k: "馬耳東風", m: "Talking to a brick wall" },
  { k: "波乱万丈", m: "Full of ups and downs; Stormy and dramatic" },
  { k: "博覧強記", m: "Extensive reading and retentive memory" },
  { k: "白砂青松", m: "White sand and green pines" },
  { k: "抜山蓋世", m: "Overwhelming strength and unmatched spirit" },
  { k: "八面玲瓏", m: "Flawless from all angles; Perfect clarity" },
  { k: "発憤興起", m: "Rousing oneself to action" },
  { k: "美辞麗句", m: "Flowery words; Rhetoric" },
  { k: "非常識的", m: "Lacking common sense; Absurd" },
  { k: "付和雷同", m: "Blindly following others" },
  { k: "不老不死", m: "Immortality; Perpetual youth and longevity" },
  { k: "不言実行", m: "Actions speak louder than words" },
  { k: "不撓不屈", m: "Indomitable; Unyielding" },
  { k: "不眠不休", m: "Without sleep or rest; Working day and night" },
  { k: "物見遊山", m: "Going on a pleasure trip; Sightseeing" },
  { k: "粉骨砕身", m: "Doing one's utmost; Working oneself to the bone" },
  { k: "平身低頭", m: "Bowing deeply and humbly apologizing" },
  { k: "平和共存", m: "Peaceful coexistence" },
  { k: "傍若無人", m: "Arrogance; Acting outrageously" },
  { k: "暴飲暴食", m: "Eating and drinking to excess" },
  { k: "本末転倒", m: "Putting the cart before the horse" },
  { k: "満場一致", m: "Unanimity; All in agreement" },
  { k: "無我夢中", m: "Being completely absorbed; Losing oneself" },
  { k: "無味乾燥", m: "Dull and uninteresting; Dry as dust" },
  { k: "無理難題", m: "Unreasonable demands" },
  { k: "明鏡止水", m: "Clear and calm mind" },
  { k: "明明白白", m: "Perfectly obvious; Clear as day" },
  { k: "面目躍如", m: "Living up to one's reputation" },
  { k: "門外不出", m: "A closely guarded secret" },
  { k: "唯我独尊", m: "Self-conceit; Thinking oneself the greatest" },
  { k: "勇往邁進", m: "Dashing forward bravely" },
  { k: "勇気凛々", m: "Full of courage" },
  { k: "油断大敵", m: "Unpreparedness is one's greatest enemy" },
  { k: "悠悠自適", m: "Living a life of quiet retirement" },
  { k: "容姿端麗", m: "Attractive face and figure" },
  { k: "羊頭狗肉", m: "Crying wine and selling vinegar" },
  { k: "用意周到", m: "Careful preparation; Thoroughness" },
  { k: "落花流水", m: "Mutual love" },
  { k: "理路整然", m: "Logical; Well-reasoned" },
  { k: "竜頭蛇尾", m: "Anti-climax; Strong start but weak finish" },
  { k: "臨機応変", m: "Adapting to circumstances" },
  { k: "臨戦態勢", m: "Readiness for action; Battle-ready" },
  { k: "冷静沈着", m: "Calm and collected" },
  { k: "和洋折衷", m: "Blending of Japanese and Western styles" },
  { k: "和気藹々", m: "Harmonious; Friendly atmosphere" },
  { k: "我慢強い", m: "Very patient; Enduring" },
  { k: "玩物喪志", m: "Losing one's ambition by playing with toys" },
  { k: "起死回生", m: "Reviving from the brink of death" },
  { k: "吉凶禍福", m: "Fortunes and misfortunes; Ups and downs" },
  { k: "興味津々", m: "Having a keen interest; Very intriguing" },
  { k: "喜色満面", m: "Beaming with joy" },
  { k: "疑心暗鬼", m: "Suspicion breeds dark demons" },
  { k: "空理空論", m: "Empty theory; Armchair arguments" },
  { k: "形影相伴", m: "Inseparable (like form and shadow)" },
  { k: "言行一致", m: "Practicing what one preaches" },
  { k: "荒唐無稽", m: "Nonsense; Absurd" },
  { k: "行雲流水", m: "Floating clouds and flowing water" },
  { k: "古今東西", m: "All times and places" },
  { k: "誇り高き", m: "Highly proud" },
  { k: "呉越同舟", m: "Bitter enemies placed in the same boat" },
  { k: "向学心旺", m: "Having a strong desire to learn" },
  { k: "剛毅朴訥", m: "Fortitude and simplicity" },
  { k: "合従連衡", m: "Diplomatic maneuvering" },
  { k: "固定観念", m: "Fixed idea; Stereotype" },
  { k: "孤立無援", m: "Isolated and helpless" },
  { k: "豪放磊落", m: "Broad-minded and big-hearted" },
  { k: "才色兼備", m: "A woman gifted with both intelligence and beauty" },
  { k: "三者三様", m: "Three people, three different ways" },
  { k: "散歩逍遥", m: "Taking a leisurely stroll" },
  { k: "四海兄弟", m: "Universal brotherhood" },
  { k: "死屍累累", m: "Heaps of corpses" },
  { k: "士魂商才", m: "Samurai spirit and merchant's talent" },
  { k: "拾遺補闕", m: "Correcting omissions and making up for defects" },
  { k: "春風駘蕩", m: "Warm spring breeze" },
  { k: "焦眉の急", m: "Imminent danger; Urgent situation" },
  { k: "小心翼翼", m: "Very timid and cautious" },
  { k: "笑裏蔵刀", m: "Hiding a dagger behind a smile" },
  { k: "人面獣心", m: "Face of a human, heart of a beast" },
  { k: "随機応変", m: "Adapting to the situation at hand" },
  { k: "寸鉄殺人", m: "A short, sharp remark that strikes home" },
  { k: "積善余慶", m: "Good deeds bring rewards to one's descendants" },
  { k: "絶世の美", m: "Matchless beauty" },
  { k: "千思万考", m: "Deep meditation; Deep thought" },
  { k: "創造破壊", m: "Creative destruction" },
  { k: "大同小異", m: "Essentially the same with minor differences" },
  { k: "大欲は無欲", m: "Great avarice is like unselfishness" },
  { k: "断崖絶壁", m: "A sheer cliff; A desperate situation" },
  { k: "沈魚落雁", m: "Beauty so great that fish sink and geese fall" },
  { k: "手前勝手", m: "Selfishness; Having one's own way" },
  { k: "天壌無窮", m: "Eternal as heaven and earth" },
  { k: "同工異曲", m: "Different execution, same result" },
  { k: "独断専行", m: "Acting on one's own authority" },
  { k: "南船北馬", m: "Constant traveling (Boats in south, horses in north)" }
];

const iChingDatabase = {
  "111111": { num: 1, name: "Qian (The Creative)", meaning: "Strong, dynamic action. Time to initiate, lead, and persevere with inner strength." },
  "000000": { num: 2, name: "Kun (The Receptive)", meaning: "Yielding, passive support. Wait and follow the current rather than forcing change." },
  "100010": { num: 3, name: "Chun (Difficulty at the Beginning)", meaning: "Chaos before order. A time of painful but necessary growth. Seek guidance." },
  "010001": { num: 4, name: "Meng (Youthful Folly)", meaning: "Inexperience. Learn from mistakes and respect the guidance of a teacher." },
  "111010": { num: 5, name: "Xu (Waiting)", meaning: "Patience. Bide your time, gather your strength, and wait for the right moment." },
  "010111": { num: 6, name: "Song (Conflict)", meaning: "Disagreement and friction. Compromise is better than pushing for a total victory." },
  "010000": { num: 7, name: "Shi (The Army)", meaning: "Discipline and organization. Align yourself with a strong purpose and leadership." },
  "000010": { num: 8, name: "Bi (Holding Together)", meaning: "Union and alliance. True connection is found in sincere cooperation." },
  "111011": { num: 9, name: "Xiao Chu (The Taming Power of the Small)", meaning: "Gentle restraint. Minor obstacles delay progress; use gentle persuasion." },
  "110111": { num: 10, name: "Lu (Treading)", meaning: "Walking cautiously. Proceed with extreme care and respect for those in power." },
  "111000": { num: 11, name: "Tai (Peace)", meaning: "Harmony and prosperity. A perfect balance of energies bringing success." },
  "000111": { num: 12, name: "Pi (Standstill)", meaning: "Stagnation. Energies are disconnected. Retreat into yourself and wait." },
  "101111": { num: 13, name: "Tong Ren (Fellowship with Men)", meaning: "Community. Success comes through cooperation and shared goals." },
  "111101": { num: 14, name: "Da You (Possession in Great Measure)", meaning: "Abundance. You have the resources and power; use them generously." },
  "001000": { num: 15, name: "Qian (Modesty)", meaning: "Humility. Balance is achieved by not boasting or overextending." },
  "000100": { num: 16, name: "Yu (Enthusiasm)", meaning: "Inspiration and movement. Channel your excitement into constructive action." },
  "100110": { num: 17, name: "Sui (Following)", meaning: "Adaptation. True leadership requires knowing when to follow and adapt." },
  "011001": { num: 18, name: "Gu (Work on what has been spoiled)", meaning: "Decay. It is time to fix past mistakes and clean out the rot." },
  "110000": { num: 19, name: "Lin (Approach)", meaning: "Advancement. Spring is coming; take advantage of the favorable timing." },
  "000011": { num: 20, name: "Guan (Contemplation)", meaning: "Observation. Step back and look at the big picture before making a move." },
  "100101": { num: 21, name: "Shi He (Biting Through)", meaning: "Overcoming obstacles. Force may be necessary to remove a blockage." },
  "101001": { num: 22, name: "Bi (Grace)", meaning: "Aesthetics and form. Superficial beauty is pleasant but lacks deep substance." },
  "000001": { num: 23, name: "Bo (Splitting Apart)", meaning: "Deterioration. Things are falling apart. Do not act; wait out the collapse." },
  "100000": { num: 24, name: "Fu (Return)", meaning: "Renewal. A turning point. The darkness has passed, and light is returning." },
  "100111": { num: 25, name: "Wu Wang (Innocence)", meaning: "Natural action. Act without ulterior motives; let things flow organically." },
  "111001": { num: 26, name: "Da Chu (The Taming Power of the Great)", meaning: "Accumulation of energy. Hold your power back until the perfect moment." },
  "100001": { num: 27, name: "Yi (The Corners of the Mouth)", meaning: "Nourishment. Pay attention to what you consume, both food and words." },
  "011110": { num: 28, name: "Da Guo (Preponderance of the Great)", meaning: "Overload. The structure is buckling under extreme pressure; act decisively." },
  "010010": { num: 29, name: "Kan (The Abysmal/Water)", meaning: "Danger. You are in deep water. Stay calm, keep moving, and be sincere." },
  "101101": { num: 30, name: "Li (The Clinging/Fire)", meaning: "Clarity and dependence. Fire needs fuel; attach yourself to what is good." },
  "001110": { num: 31, name: "Xian (Influence)", meaning: "Mutual attraction. Open yourself to the influence of others and connect." },
  "011100": { num: 32, name: "Heng (Duration)", meaning: "Consistency. Success comes through steady, unchanging persistence." },
  "001111": { num: 33, name: "Dun (Retreat)", meaning: "Strategic withdrawal. Pull back from a losing battle to preserve your strength." },
  "111100": { num: 34, name: "Da Zhuang (The Power of the Great)", meaning: "Immense power. Use your strength justly and avoid reckless aggression." },
  "000101": { num: 35, name: "Jin (Progress)", meaning: "Rapid advancement. The sun is rising; step into the light and succeed." },
  "101000": { num: 36, name: "Ming I (Darkening of the Light)", meaning: "Adversity. Hide your light and lay low while surrounded by darkness." },
  "101011": { num: 37, name: "Jia Ren (The Family)", meaning: "Inner structures. Focus on domestic harmony and the roles within a group." },
  "110101": { num: 38, name: "Kui (Opposition)", meaning: "Misunderstanding. People are working at cross-purposes. Find small agreements." },
  "001010": { num: 39, name: "Jian (Obstruction)", meaning: "Impassable blockage. Do not push forward; retreat and ask for advice." },
  "010100": { num: 40, name: "Xie (Deliverance)", meaning: "Relief. The tension has broken. Forgive, forget, and move on swiftly." },
  "110001": { num: 41, name: "Sun (Decrease)", meaning: "Letting go. Give up the non-essential to achieve a greater simplicity." },
  "100011": { num: 42, name: "Yi (Increase)", meaning: "Expansion. A time of great opportunity and blessing. Act boldly." },
  "111110": { num: 43, name: "Guai (Breakthrough)", meaning: "Resolution. Firmly but carefully remove corrupt influences." },
  "011111": { num: 44, name: "Gou (Coming to Meet)", meaning: "Unexpected encounters. Beware of seemingly harmless but dangerous temptations." },
  "000110": { num: 45, name: "Cui (Gathering Together)", meaning: "Massing. Bring people and resources together for a common cause." },
  "011000": { num: 46, name: "Sheng (Pushing Upward)", meaning: "Steady growth. Like a tree growing from the earth, rise slowly and surely." },
  "010110": { num: 47, name: "Kun (Oppression)", meaning: "Exhaustion. Resources are drained. Hold on to your inner truth and wait." },
  "011010": { num: 48, name: "Jing (The Well)", meaning: "Source. The fundamental needs of life remain unchanged. Go to the source." },
  "101110": { num: 49, name: "Ge (Revolution)", meaning: "Radical change. Shed the old skin; a necessary overthrow of the old order." },
  "011101": { num: 50, name: "Ding (The Caldron)", meaning: "Transformation. A spiritual and cultural refinement bringing high success." },
  "100100": { num: 51, name: "Zhen (The Arousing/Thunder)", meaning: "Shock. A sudden, terrifying event that brings necessary awakening." },
  "001001": { num: 52, name: "Gen (Keeping Still/Mountain)", meaning: "Stillness. Stop all movement. Quiet your mind and find inner peace." },
  "001011": { num: 53, name: "Jian (Development/Gradual Progress)", meaning: "Slow progress. Do not rush; let things unfold at their natural pace." },
  "110100": { num: 54, name: "Gui Mei (The Marrying Maiden)", meaning: "Subordination. You are in a disadvantageous position. Accept your limits." },
  "101100": { num: 55, name: "Feng (Abundance)", meaning: "Zenith. Peak prosperity, but recognize that peaks are followed by declines." },
  "001101": { num: 56, name: "Lu (The Wanderer)", meaning: "Travel. You are an outsider. Be cautious, adaptable, and respectful." },
  "011011": { num: 57, name: "Xun (The Gentle/Wind)", meaning: "Penetration. Gentle, persistent effort over time yields massive results." },
  "110110": { num: 58, name: "Dui (The Joyous/Lake)", meaning: "Joy. True happiness comes through open communication and shared pleasure." },
  "010011": { num: 59, name: "Huan (Dispersion)", meaning: "Dissolving. Illusions and blockages are clearing. Let things flow apart naturally." },
  "110010": { num: 60, name: "Jie (Limitation)", meaning: "Boundaries. Set healthy limits and stick to a defined budget or structure." },
  "110011": { num: 61, name: "Zhong Fu (Inner Truth)", meaning: "Sincerity. Profound trust and honesty have the power to influence even the hardest hearts." },
  "001100": { num: 62, name: "Xiao Guo (Preponderance of the Small)", meaning: "Small measures. Keep a low profile and focus on minor, practical details." },
  "101010": { num: 63, name: "Ji Ji (After Completion)", meaning: "Order achieved. Everything is in its place, but stay alert to prevent future decay." },
  "010101": { num: 64, name: "Wei Ji (Before Completion)", meaning: "Threshold. The transition is incomplete. Proceed with extreme caution." }
};

const ccruLexicon = [
  { term: "Abomenon", def: "Postulated substrate of absolute horror (the worst thing in the world)." }, 
  { term: "A-Death", def: "Neuroelectronic flatline, based upon Sarkonian mesh-engineering." }, 
  { term: "Ccru", def: "Cryptic hyperstitional entity." }, 
  { term: "Cthelll", def: "Earth's iron ocean, comprising one third of terrestrial mass." }, 
  { term: "Lemuria", def: "Hypergeographical terrestrial arrangement." }, 
  { term: "Numogram", def: "Diagrammatization of decimal numeracy, providing the key to Lemurian culture." }, 
  { term: "Pandemonium", def: "Utterminus of Cthelll. Comprehensive system of the demons." }, 
  { term: "Time-Sorcery", def: "Counterchronic effectuation of the Numogram." }, 
  { term: "Tic-Systems", def: "Consistent microstimular assemblages dismantling semiotic regimes onto a flat machinic plane." }
];

const randomPhrases = [ 
  { text: "¡Qué nota, parcero! ¡A estudiar se dijo!", lang: "rolo", label: "ROLO" }, 
  { text: "No sea tan ñero, póngase las pilas.", lang: "rolo", label: "ROLO" }, 
  { text: "¡Uy, hermano, qué chimba de racha!", lang: "rolo", label: "ROLO" }, 
  { text: "Mijo, no joda, estudie que le conviene.", lang: "rolo", label: "ROLO" }, 
  { text: "よっしゃ！今日もがんばろう！", lang: "nihongo", label: "日本語" }, 
  { text: "すごいじゃん！その調子！", lang: "nihongo", label: "日本語" }, 
  { text: "勉強は大事だよ、ファイト！", lang: "nihongo", label: "日本語" } 
];

const starterDeck = [ { en: "To read", jp: "読む", es: "Leer" }, { en: "Street", jp: "通り", es: "Calle" }, { en: "Store", jp: "店", es: "Tienda" } ];
