/**
 * DATA.JS - The Oracle & Moe-Chan Database
 * This file contains all the dictionaries and references for the app.
 */

// 1. ALL 64 I-CHING HEXAGRAMS
const iChingDatabase = {
  "111111": { num: 1, name: "Qian (The Creative)", meaning: "Strong, dynamic action. Time to initiate, lead, and persevere with inner strength." },
  "000000": { num: 2, name: "Kun (The Receptive)", meaning: "Yielding, passive support. Wait and follow the current rather than forcing change." },
  "100010": { num: 3, name: "Chun (Difficulty at the Beginning)", meaning: "Chaos before order. A time of painful but necessary growth. Seek guidance." },
  "010001": { num: 4, name: "Meng (Youthful Folly)", meaning: "Inexperience. Learn from mistakes and respect the guidance of a teacher." },
  "111010": { num: 5, name: "Xu (Waiting)", meaning: "Patience. Bide your time, gather your strength, and wait for the right moment." },
  "010111": { num: 6, name: "Song (Conflict)", meaning: "Disagreement and friction. Compromise is better than pushing for a total victory." },
  "010000": { num: 7, name: "Shi (The Army)", meaning: "Discipline and organization. Align yourself with a strong purpose and leadership." },
  "000010": { num: 8, name: "Bi (Holding Together)", meaning: "Union and alliance. True connection is found in sincere cooperation." },
  "111011": { num: 9, name: "Xiao Chu (The Taming Power of the Small)", meaning: "Gentle restraint. Minor obstacles delay progress; use gentle persuasion." },
  "110111": { num: 10, name: "Lu (Treading)", meaning: "Walking cautiously. Proceed with extreme care and respect for those in power." },
  "111000": { num: 11, name: "Tai (Peace)", meaning: "Harmony and prosperity. A perfect balance of energies bringing success." },
  "000111": { num: 12, name: "Pi (Standstill)", meaning: "Stagnation. Energies are disconnected. Retreat into yourself and wait." },
  "101111": { num: 13, name: "Tong Ren (Fellowship with Men)", meaning: "Community. Success comes through cooperation and shared goals." },
  "111101": { num: 14, name: "Da You (Possession in Great Measure)", meaning: "Abundance. You have the resources and power; use them generously." },
  "001000": { num: 15, name: "Qian (Modesty)", meaning: "Humility. Balance is achieved by not boasting or overextending." },
  "000100": { num: 16, name: "Yu (Enthusiasm)", meaning: "Inspiration and movement. Channel your excitement into constructive action." },
  "100110": { num: 17, name: "Sui (Following)", meaning: "Adaptation. True leadership requires knowing when to follow and adapt." },
  "011001": { num: 18, name: "Gu (Work on what has been spoiled)", meaning: "Decay. It is time to fix past mistakes and clean out the rot." },
  "110000": { num: 19, name: "Lin (Approach)", meaning: "Advancement. Spring is coming; take advantage of the favorable timing." },
  "000011": { num: 20, name: "Guan (Contemplation)", meaning: "Observation. Step back and look at the big picture before making a move." },
  "100101": { num: 21, name: "Shi He (Biting Through)", meaning: "Overcoming obstacles. Force may be necessary to remove a blockage." },
  "101001": { num: 22, name: "Bi (Grace)", meaning: "Aesthetics and form. Superficial beauty is pleasant but lacks deep substance." },
  "000001": { num: 23, name: "Bo (Splitting Apart)", meaning: "Deterioration. Things are falling apart. Do not act; wait out the collapse." },
  "100000": { num: 24, name: "Fu (Return)", meaning: "Renewal. A turning point. The darkness has passed, and light is returning." },
  "100111": { num: 25, name: "Wu Wang (Innocence)", meaning: "Natural action. Act without ulterior motives; let things flow organically." },
  "111001": { num: 26, name: "Da Chu (The Taming Power of the Great)", meaning: "Accumulation of energy. Hold your power back until the perfect moment." },
  "100001": { num: 27, name: "Yi (The Corners of the Mouth)", meaning: "Nourishment. Pay attention to what you consume, both food and words." },
  "011110": { num: 28, name: "Da Guo (Preponderance of the Great)", meaning: "Overload. The structure is buckling under extreme pressure; act decisively." },
  "010010": { num: 29, name: "Kan (The Abysmal/Water)", meaning: "Danger. You are in deep water. Stay calm, keep moving, and be sincere." },
  "101101": { num: 30, name: "Li (The Clinging/Fire)", meaning: "Clarity and dependence. Fire needs fuel; attach yourself to what is good." },
  "001110": { num: 31, name: "Xian (Influence)", meaning: "Mutual attraction. Open yourself to the influence of others and connect." },
  "011100": { num: 32, name: "Heng (Duration)", meaning: "Consistency. Success comes through steady, unchanging persistence." },
  "001111": { num: 33, name: "Dun (Retreat)", meaning: "Strategic withdrawal. Pull back from a losing battle to preserve your strength." },
  "111100": { num: 34, name: "Da Zhuang (The Power of the Great)", meaning: "Immense power. Use your strength justly and avoid reckless aggression." },
  "000101": { num: 35, name: "Jin (Progress)", meaning: "Rapid advancement. The sun is rising; step into the light and succeed." },
  "101000": { num: 36, name: "Ming I (Darkening of the Light)", meaning: "Adversity. Hide your light and lay low while surrounded by darkness." },
  "101011": { num: 37, name: "Jia Ren (The Family)", meaning: "Inner structures. Focus on domestic harmony and the roles within a group." },
  "110101": { num: 38, name: "Kui (Opposition)", meaning: "Misunderstanding. People are working at cross-purposes. Find small agreements." },
  "001010": { num: 39, name: "Jian (Obstruction)", meaning: "Impassable blockage. Do not push forward; retreat and ask for advice." },
  "010100": { num: 40, name: "Xie (Deliverance)", meaning: "Relief. The tension has broken. Forgive, forget, and move on swiftly." },
  "110001": { num: 41, name: "Sun (Decrease)", meaning: "Letting go. Give up the non-essential to achieve a greater simplicity." },
  "100011": { num: 42, name: "Yi (Increase)", meaning: "Expansion. A time of great opportunity and blessing. Act boldly." },
  "111110": { num: 43, name: "Guai (Breakthrough)", meaning: "Resolution. Firmly but carefully remove corrupt influences." },
  "011111": { num: 44, name: "Gou (Coming to Meet)", meaning: "Unexpected encounters. Beware of seemingly harmless but dangerous temptations." },
  "000110": { num: 45, name: "Cui (Gathering Together)", meaning: "Massing. Bring people and resources together for a common cause." },
  "011000": { num: 46, name: "Sheng (Pushing Upward)", meaning: "Steady growth. Like a tree growing from the earth, rise slowly and surely." },
  "010110": { num: 47, name: "Kun (Oppression)", meaning: "Exhaustion. Resources are drained. Hold on to your inner truth and wait." },
  "011010": { num: 48, name: "Jing (The Well)", meaning: "Source. The fundamental needs of life remain unchanged. Go to the source." },
  "101110": { num: 49, name: "Ge (Revolution)", meaning: "Radical change. Shed the old skin; a necessary overthrow of the old order." },
  "011101": { num: 50, name: "Ding (The Caldron)", meaning: "Transformation. A spiritual and cultural refinement bringing high success." },
  "100100": { num: 51, name: "Zhen (The Arousing/Thunder)", meaning: "Shock. A sudden, terrifying event that brings necessary awakening." },
  "001001": { num: 52, name: "Gen (Keeping Still/Mountain)", meaning: "Stillness. Stop all movement. Quiet your mind and find inner peace." },
  "001011": { num: 53, name: "Jian (Development/Gradual Progress)", meaning: "Slow progress. Do not rush; let things unfold at their natural pace." },
  "110100": { num: 54, name: "Gui Mei (The Marrying Maiden)", meaning: "Subordination. You are in a disadvantageous position. Accept your limits." },
  "101100": { num: 55, name: "Feng (Abundance)", meaning: "Zenith. Peak prosperity, but recognize that peaks are followed by declines." },
  "001101": { num: 56, name: "Lu (The Wanderer)", meaning: "Travel. You are an outsider. Be cautious, adaptable, and respectful." },
  "011011": { num: 57, name: "Xun (The Gentle/Wind)", meaning: "Penetration. Gentle, persistent effort over time yields massive results." },
  "110110": { num: 58, name: "Dui (The Joyous/Lake)", meaning: "Joy. True happiness comes through open communication and shared pleasure." },
  "010011": { num: 59, name: "Huan (Dispersion)", meaning: "Dissolving. Illusions and blockages are clearing. Let things flow apart naturally." },
  "110010": { num: 60, name: "Jie (Limitation)", meaning: "Boundaries. Set healthy limits and stick to a defined budget or structure." },
  "110011": { num: 61, name: "Zhong Fu (Inner Truth)", meaning: "Sincerity. Profound trust and honesty have the power to influence even the hardest hearts." },
  "001100": { num: 62, name: "Xiao Guo (Preponderance of the Small)", meaning: "Small measures. Keep a low profile and focus on minor, practical details." },
  "101010": { num: 63, name: "Ji Ji (After Completion)", meaning: "Order achieved. Everything is in its place, but stay alert to prevent future decay." },
  "010101": { num: 64, name: "Wei Ji (Before Completion)", meaning: "Threshold. The transition is incomplete. Proceed with extreme caution." }
};

// 2. YOJIJUKUGO FULL LIST
const yojijukugoList = [
  { k: "一石二鳥", m: "Killing two birds with one stone" },
  { k: "一刀両断", m: "Cutting in two with a single stroke; Taking decisive action" },
  { k: "一期一会", m: "Once-in-a-lifetime encounter; Treasure every meeting" },
  { k: "一心不乱", m: "With heart and soul; Intently and focused" },
  { k: "一念発起", m: "Being resolved to do something; Turning over a new leaf" },
  { k: "一長一短", m: "Merits and demerits; Having both strong and weak points" },
  { k: "一朝一夕", m: "In a single day; Overnight (usually 'cannot be done overnight')" },
  { k: "一喜一憂", m: "Alternating between joy and sorrow; Emotional rollercoaster" },
  { k: "一蓮托生", m: "Sharing the same fate; Being in the same boat" },
  { k: "一触即発", m: "Volatile situation; Touch-and-go" },
  { k: "一進一退", m: "One step forward, one step back; Ebbing and flowing" },
  { k: "一致団結", m: "Solidarity; Uniting as one" },
  { k: "一日千秋", m: "Waiting impatiently; One day feels like a thousand years" },
  { k: "一笑千金", m: "A smile worth a thousand pieces of gold; Captivating smile" },
  { k: "一言一句", m: "Every single word and phrase" },
  { k: "一挙両得", m: "Serving two purposes; Two birds with one stone" },
  { k: "一挙一動", m: "Every single move and action" },
  { k: "一夜漬け", m: "Cramming overnight for an exam" },
  { k: "一世一代", m: "Once in a lifetime event or performance" },
  { k: "一目瞭然", m: "Apparent at a glance; Obvious" },
  { k: "二人三脚", m: "Two people acting as one; Three-legged race" },
  { k: "二束三文", m: "Dirt cheap; A dime a dozen" },
  { k: "三位一体", m: "Trinity; Three things coming together as one" },
  { k: "三寒四温", m: "Three cold days followed by four warm days" },
  { k: "三十六計", m: "Of the 36 strategies, fleeing is best" },
  { k: "三日坊主", m: "One who gives up easily; A monk for three days" },
  { k: "四面楚歌", m: "Surrounded by enemies on all sides; Total isolation" },
  { k: "四苦八苦", m: "Being in dire distress; Agonizing" },
  { k: "四字熟語", m: "Four-character idiom" },
  { k: "五里霧中", m: "Lost in a fog; Totally bewildered" },
  { k: "五臓六腑", m: "The internal organs; From the bottom of one's heart" },
  { k: "七転八倒", m: "Writhing in agony; Tumbling and falling" },
  { k: "七転び八起き", m: "Fall down seven times, stand up eight; Resilience" },
  { k: "八方美人", m: "Trying to please everyone; Everybody's friend" },
  { k: "八面六臂", m: "Highly versatile; Having eight faces and six arms" },
  { k: "十人十色", m: "Ten people, ten colors; To each their own" },
  { k: "百花繚乱", m: "A hundred flowers blooming; Gathering of talent" },
  { k: "百戦錬磨", m: "Veteran of a hundred battles; Highly experienced" },
  { k: "百発百中", m: "On target every time; Infallible" },
  { k: "百聞は一見", m: "Seeing is believing; A picture worth a thousand words" },
  { k: "千変万化", m: "Innumerable changes; Kaleidoscopic" },
  { k: "千差万別", m: "An infinite variety of differences; Apples and oranges" },
  { k: "千載一遇", m: "Once in a thousand years opportunity" },
  { k: "千客万来", m: "A constant stream of customers" },
  { k: "万里の長城", m: "The Great Wall of China" },
  { k: "万事休す", m: "All is lost; Nothing more to be done" },
  { k: "万骨枯る", m: "Thousands perish so one general can achieve fame" },
  { k: "万全の策", m: "A foolproof plan; A perfect strategy" },
  { k: "以心伝心", m: "Telepathy; Heart-to-heart communication" },
  { k: "異口同音", m: "Unanimously; Speaking with one voice" },
  { k: "異端邪説", m: "Heresy and false doctrines" },
  { k: "意気投合", m: "Hitting it off; Finding a kindred spirit" },
  { k: "意気消沈", m: "Depressed; Downhearted" },
  { k: "意気軒昂", m: "In high spirits; Triumphant" },
  { k: "意味深長", m: "Profound meaning; Full of implications" },
  { k: "因果応報", m: "Karma; What goes around comes around" },
  { k: "隠忍自重", m: "Putting up with things patiently" },
  { k: "有象無象", m: "The masses; The rabble; Mob" },
  { k: "右往左往", m: "Going back and forth in confusion; Panicking" },
  { k: "有名無実", m: "In name only; Existing only in name" },
  { k: "紆余曲折", m: "Twists and turns; Meandering" },
  { k: "海千山千", m: "A sly old dog; Knowing the ways of the world" },
  { k: "快刀乱麻", m: "Solving a complex problem decisively" },
  { k: "外柔内剛", m: "Gentle on the outside, tough on the inside" },
  { k: "臥薪嘗胆", m: "Enduring hardships for the sake of success" },
  { k: "我田引水", m: "Seeking one's own interests; Drawing water to one's field" },
  { k: "夏炉冬扇", m: "Useless things (Summer heater, Winter fan)" },
  { k: "花鳥風月", m: "The beauties of nature; Flower, Bird, Wind, Moon" },
  { k: "花鳥諷詠", m: "Composing poetry on the beauties of nature" },
  { k: "画竜点睛", m: "Finishing touch; Putting the pupils in the dragon's eyes" },
  { k: "換骨奪胎", m: "Adapting an old work to create something new" },
  { k: "勧善懲悪", m: "Rewarding good and punishing evil" },
  { k: "感慨無量", m: "Deeply moved; Filled with deep emotion" },
  { k: "冠婚葬祭", m: "Important ceremonial occasions" },
  { k: "危機一髪", m: "Hanging by a thread; A hair's breadth from danger" },
  { k: "喜怒哀楽", m: "Human emotions; Joy, anger, sorrow, and pleasure" },
  { k: "奇想天外", m: "Fantastic; Bizarre; Completely unexpected" },
  { k: "玉石混交", m: "Good and bad mixed together" },
  { k: "旧態依然", m: "Remaining unchanged; Stuck in the old ways" },
  { k: "九牛一毛", m: "A drop in the bucket; One hair from nine cows" },
  { k: "共存共栄", m: "Coexistence and coprosperity" },
  { k: "虚心坦懐", m: "With an open and calm mind" },
  { k: "欣喜雀躍", m: "Jumping for joy" },
  { k: "空前絶後", m: "Unprecedented and never to be repeated" },
  { k: "軽挙妄動", m: "Rash and blind action" },
  { k: "継往開来", m: "Inheriting the past and ushering in the future" },
  { k: "鶏口牛後", m: "Better to be the head of a chicken than the tail of a cow" },
  { k: "形而上学", m: "Metaphysics" },
  { k: "傾国傾城", m: "A woman of matchless beauty" },
  { k: "激励鼓舞", m: "Encouragement and inspiration" },
  { k: "堅忍不抜", m: "Indomitable perseverance; Unshakable resolve" },
  { k: "乾坤一擲", m: "Staking everything on a single throw" },
  { k: "言語道断", m: "Outrageous; Absurd; Unspeakable" },
  { k: "孤軍奮闘", m: "Fighting a lone battle" },
  { k: "虎視眈眈", m: "Watching vigilantly for an opportunity" },
  { k: "誇大妄想", m: "Megalomania; Delusions of grandeur" },
  { k: "五穀豊穣", m: "Bountiful harvest" },
  { k: "山紫水明", m: "Scenic beauty of mountains and rivers" },
  { k: "獅子奮迅", m: "Fighting like a raging lion" },
  { k: "四分五裂", m: "Torn to pieces; Completely fragmented" },
  { k: "自業自得", m: "Reaping what you sow" },
  { k: "自給自足", m: "Self-sufficiency" },
  { k: "自画自賛", m: "Singing one's own praises" },
  { k: "自暴自棄", m: "Desperation; Abandoning oneself to despair" },
  { k: "自由奔放", m: "Free and unrestrained; Free-spirited" },
  { k: "自縄自縛", m: "Being caught in one's own trap" },
  { k: "疾風迅雷", m: "With lightning speed; Swift and violent" },
  { k: "質実剛健", m: "Sincere with fortitude and vigor" },
  { k: "捲土重来", m: "Making a comeback with redoubled efforts" },
  { k: "遮二無二", m: "Recklessly; Frantically" },
  { k: "弱肉強食", m: "Survival of the fittest" },
  { k: "取捨選択", m: "Choosing the good and rejecting the bad" },
  { k: "首尾一貫", m: "Consistency from beginning to end" },
  { k: "縦横無尽", m: "Freely; Without restriction" },
  { k: "熟慮断行", m: "Deliberate carefully and act decisively" },
  { k: "春夏秋冬", m: "The four seasons" },
  { k: "純情可憐", m: "Pure and innocent; Sweet and lovely" },
  { k: "諸行無常", m: "All things are transitory; Impermanence" },
  { k: "初志貫徹", m: "Carrying out original intention to the end" },
  { k: "心機一転", m: "Turning over a new leaf" },
  { k: "針小棒大", m: "Making a mountain out of a molehill" },
  { k: "森羅万象", m: "All of creation; The universe" },
  { k: "深謀遠慮", m: "Deep foresight and careful planning" },
  { k: "神出鬼没", m: "Elusive; Appearing like a phantom" },
  { k: "晴耕雨読", m: "Work in the sun, read in the rain" },
  { k: "生殺与奪", m: "Power of life and death over someone" },
  { k: "正真正銘", m: "Genuine; Authentic" },
  { k: "清廉潔白", m: "Upright and clean-handed" },
  { k: "絶体絶命", m: "Driven into a corner; Desperate" },
  { k: "前代未聞", m: "Unprecedented; Unheard-of" },
  { k: "前途洋洋", m: "Promising future" },
  { k: "前途多難", m: "Many difficulties ahead" },
  { k: "創意工夫", m: "Being imaginative and creative" },
  { k: "相思相愛", m: "Mutual love" },
  { k: "大器晩成", m: "Great talents mature late" },
  { k: "大言壮語", m: "Talking big; Boasting" },
  { k: "大義名分", m: "Just cause; Legitimate reason" },
  { k: "単刀直入", m: "Getting straight to the point" },
  { k: "知行合一", m: "Action and knowledge are one" },
  { k: "中途半端", m: "Halfway; Incomplete" },
  { k: "朝令暮改", m: "Inconsistent policies" },
  { k: "直情径行", m: "Acting on impulse" },
  { k: "沈思黙考", m: "Deep in thought; Musing" },
  { k: "天下泰平", m: "Peace in the world" },
  { k: "天真爛漫", m: "Innocent and naive" },
  { k: "天変地異", m: "Natural disasters; Cataclysms" },
  { k: "天衣無縫", m: "Flawless; Perfect beauty" },
  { k: "天地無用", m: "Do not turn upside down" },
  { k: "電光石火", m: "As fast as lightning" },
  { k: "徹頭徹尾", m: "Thoroughly; Through and through" },
  { k: "転禍為福", m: "Turning misfortune into a blessing" },
  { k: "唯唯諾諾", m: "Being a yes-man" },
  { k: "同床異夢", m: "Same bed, different dreams" },
  { k: "道聴塗説", m: "Gossip; Hearsay" },
  { k: "独立独歩", m: "Standing on one's own two feet" },
  { k: "読書三昧", m: "Engrossed in reading" },
  { k: "内憂外患", m: "Troubles at home and abroad" },
  { k: "難攻不落", m: "Impregnable; Invincible" },
  { k: "二者択一", m: "Choosing between two options" },
  { k: "日進月歩", m: "Rapid and steady progress" },
  { k: "入木三分", m: "Leaving a deep impression" },
  { k: "忍之一字", m: "Endurance is everything" },
  { k: "馬耳東風", m: "Talking to a brick wall" },
  { k: "波乱万丈", m: "Full of ups and downs; Dramatic" },
  { k: "博覧強記", m: "Extensive reading and retentive memory" },
  { k: "白砂青松", m: "Beautiful coastal scenery" },
  { k: "抜山蓋世", m: "Overwhelming strength" },
  { k: "八面玲瓏", m: "Flawless from all angles" },
  { k: "発憤興起", m: "Rousing oneself to action" },
  { k: "美辞麗句", m: "Flowery words; Rhetoric" },
  { k: "非常識的", m: "Lacking common sense" },
  { k: "付和雷同", m: "Jumping on the bandwagon" },
  { k: "不老不死", m: "Immortality; Perpetual youth" },
  { k: "不言実行", m: "Actions speak louder than words" },
  { k: "不撓不屈", m: "Indomitable; Unyielding" },
  { k: "不眠不休", m: "Working day and night" },
  { k: "物見遊山", m: "Sightseeing" },
  { k: "粉骨砕身", m: "Working oneself to the bone" },
  { k: "平身低頭", m: "Humbly apologizing" },
  { k: "平和共存", m: "Peaceful coexistence" },
  { k: "傍若無人", m: "Arrogance; Outrageous behavior" },
  { k: "暴飲暴食", m: "Eating and drinking to excess" },
  { k: "本末転倒", m: "Putting the cart before the horse" },
  { k: "満場一致", m: "Unanimously" },
  { k: "無我夢中", m: "Completely absorbed; Losing oneself" },
  { k: "無味乾燥", m: "Dull and uninteresting" },
  { k: "無理難題", m: "Unreasonable demands" },
  { k: "明鏡止水", m: "A mind as clear as still water" },
  { k: "明明白白", m: "Perfectly obvious" },
  { k: "面目躍如", m: "Living up to one's reputation" },
  { k: "門外不出", m: "A closely guarded secret" },
  { k: "唯我独尊", m: "Thinking oneself the greatest" },
  { k: "勇往邁進", m: "Dashing forward bravely" },
  { k: "勇気凛々", m: "Full of courage" },
  { k: "油断大敵", m: "Carelessness costs dearly" },
  { k: "悠悠自適", m: "Quiet retirement" },
  { k: "容姿端麗", m: "Attractive face and figure" },
  { k: "羊頭狗肉", m: "False advertising" },
  { k: "用意周到", m: "Thorough preparation" },
  { k: "落花流水", m: "Mutual love" },
  { k: "理路整然", m: "Logical; Well-reasoned" },
  { k: "竜頭蛇尾", m: "Strong start, weak finish" },
  { k: "臨機応変", m: "Adapting to circumstances" },
  { k: "臨戦態勢", m: "Battle-ready" },
  { k: "冷静沈着", m: "Calm and collected" },
  { k: "和洋折衷", m: "Blending Japanese and Western styles" },
  { k: "和気藹々", m: "Harmonious atmosphere" },
  { k: "南船北馬", m: "Constant traveling" }
];

// 3. CCRU LEXICON
const ccruLexicon = [
  { term: "Abomenon", def: "Postulated substrate of absolute horror." },
  { term: "A-Death", def: "Neuroelectronic flatline, based upon Sarkonian mesh-engineering." },
  { term: "Ccru", def: "Cryptic hyperstitional entity." },
  { term: "Cthelll", def: "Earth's iron ocean, comprising one third of terrestrial mass." },
  { term: "Lemuria", def: "Hypergeographical terrestrial arrangement." },
  { term: "Numogram", def: "Diagrammatization of decimal numeracy." },
  { term: "Pandemonium", def: "Utterminus of Cthelll. System of the demons." },
  { term: "Time-Sorcery", def: "Counterchronic effectuation of the Numogram." },
  { term: "Tic-Systems", def: "Microstimular assemblages dismantling semiotic regimes." }
];

// 4. RANDOM PHRASES
const randomPhrases = [
  { text: "¡Qué nota, parcero! ¡A estudiar!", lang: "rolo", label: "ROLO" },
  { text: "No sea tan ñero, póngase las pilas.", lang: "rolo", label: "ROLO" },
  { text: "¡Uy, hermano, qué chimba de racha!", lang: "rolo", label: "ROLO" },
  { text: "Mijo, no joda, estudie que le conviene.", lang: "rolo", label: "ROLO" },
  { text: "よっしゃ！今日もがんばろう！", lang: "nihongo", label: "日本語" },
  { text: "すごいじゃん！その調子！", lang: "nihongo", label: "日本語" },
  { text: "勉強は大事だよ、ファイト！", lang: "nihongo", label: "日本語" }
];

// 5. STARTER DICTIONARY DECK
const starterDeck = [
  { en: "To read", jp: "読む", es: "Leer" },
  { en: "Street", jp: "通り", es: "Calle" },
  { en: "Store", jp: "店", es: "Tienda" }
];
